<?php

namespace fur\bright\utils;

class BrightStatic {
	
	public static $countries = array(
			'AF' => array('code' => 'AF', 'nl' => 'Afghanistan'),
			'AX' => array('code' => 'AX', 'nl' => 'Ã…land'),
			'AL' => array('code' => 'AL', 'nl' => 'AlbaniÃ«'),
			'DZ' => array('code' => 'DZ', 'nl' => 'Algerije'),
			'VI' => array('code' => 'VI', 'nl' => 'Amerikaanse Maagdeneilanden'),
			'AS' => array('code' => 'AS', 'nl' => 'Amerikaans-Samoa'),
			'AD' => array('code' => 'AD', 'nl' => 'Andorra'),
			'AO' => array('code' => 'AO', 'nl' => 'Angola'),
			'AI' => array('code' => 'AI', 'nl' => 'Anguilla'),
			'AQ' => array('code' => 'AQ', 'nl' => 'Antarctica'),
			'AG' => array('code' => 'AG', 'nl' => 'Antigua en Barbuda'),
			'AR' => array('code' => 'AR', 'nl' => 'ArgentiniÃ«'),
			'AM' => array('code' => 'AM', 'nl' => 'ArmeniÃ«'),
			'AW' => array('code' => 'AW', 'nl' => 'Aruba'),
			'AU' => array('code' => 'AU', 'nl' => 'AustraliÃ«'),
			'AZ' => array('code' => 'AZ', 'nl' => 'Azerbeidzjan'),
			'BS' => array('code' => 'BS', 'nl' => 'Bahama\'s'),
			'BH' => array('code' => 'BH', 'nl' => 'Bahrein'),
			'BD' => array('code' => 'BD', 'nl' => 'Bangladesh'),
			'BB' => array('code' => 'BB', 'nl' => 'Barbados'),
			'BE' => array('code' => 'BE', 'nl' => 'BelgiÃ«'),
			'BZ' => array('code' => 'BZ', 'nl' => 'Belize'),
			'BJ' => array('code' => 'BJ', 'nl' => 'Benin'),
			'BM' => array('code' => 'BM', 'nl' => 'Bermuda'),
			'BT' => array('code' => 'BT', 'nl' => 'Bhutan'),
			'BO' => array('code' => 'BO', 'nl' => 'Bolivia'),
			'BQ' => array('code' => 'BQ', 'nl' => 'Bonaire, Sint Eustatius en Saba'),
			'BA' => array('code' => 'BA', 'nl' => 'BosniÃ« en Herzegovina'),
			'BW' => array('code' => 'BW', 'nl' => 'Botswana'),
			'BV' => array('code' => 'BV', 'nl' => 'Bouvet'),
			'BR' => array('code' => 'BR', 'nl' => 'BraziliÃ«'),
			'VG' => array('code' => 'VG', 'nl' => 'Britse Maagdeneilanden'),
			'IO' => array('code' => 'IO', 'nl' => 'Brits Indische Oceaanterritorium'),
			'BN' => array('code' => 'BN', 'nl' => 'Brunei'),
			'BG' => array('code' => 'BG', 'nl' => 'Bulgarije'),
			'BF' => array('code' => 'BF', 'nl' => 'Burkina Faso'),
			'BI' => array('code' => 'BI', 'nl' => 'Burundi'),
			'KH' => array('code' => 'KH', 'nl' => 'Cambodja'),
			'CA' => array('code' => 'CA', 'nl' => 'Canada'),
			'CF' => array('code' => 'CF', 'nl' => 'Centraal-Afrikaanse Republiek'),
			'CL' => array('code' => 'CL', 'nl' => 'Chili'),
			'CN' => array('code' => 'CN', 'nl' => 'China'),
			'CX' => array('code' => 'CX', 'nl' => 'Christmaseiland'),
			'CC' => array('code' => 'CC', 'nl' => 'Cocoseilanden'),
			'CO' => array('code' => 'CO', 'nl' => 'Colombia'),
			'KM' => array('code' => 'KM', 'nl' => 'Comoren'),
			'CG' => array('code' => 'CG', 'nl' => 'Congo-Brazzaville'),
			'CD' => array('code' => 'CD', 'nl' => 'Congo-Kinshasa'),
			'CK' => array('code' => 'CK', 'nl' => 'Cookeilanden'),
			'CR' => array('code' => 'CR', 'nl' => 'Costa Rica'),
			'CU' => array('code' => 'CU', 'nl' => 'Cuba'),
			'CW' => array('code' => 'CW', 'nl' => 'CuraÃ§ao'),
			'CY' => array('code' => 'CY', 'nl' => 'Cyprus'),
			'DK' => array('code' => 'DK', 'nl' => 'Denemarken'),
			'DJ' => array('code' => 'DJ', 'nl' => 'Djibouti'),
			'DM' => array('code' => 'DM', 'nl' => 'Dominica'),
			'DO' => array('code' => 'DO', 'nl' => 'Dominicaanse Republiek'),
			'DE' => array('code' => 'DE', 'nl' => 'Duitsland'),
			'EC' => array('code' => 'EC', 'nl' => 'Ecuador'),
			'EG' => array('code' => 'EG', 'nl' => 'Egypte'),
			'SV' => array('code' => 'SV', 'nl' => 'El Salvador'),
			'GQ' => array('code' => 'GQ', 'nl' => 'Equatoriaal-Guinea'),
			'ER' => array('code' => 'ER', 'nl' => 'Eritrea'),
			'EE' => array('code' => 'EE', 'nl' => 'Estland'),
			'ET' => array('code' => 'ET', 'nl' => 'EthiopiÃ«'),
			'FO' => array('code' => 'FO', 'nl' => 'FaerÃ¶er'),
			'FK' => array('code' => 'FK', 'nl' => 'Falklandeilanden'),
			'FJ' => array('code' => 'FJ', 'nl' => 'Fiji'),
			'PH' => array('code' => 'PH', 'nl' => 'Filipijnen'),
			'FI' => array('code' => 'FI', 'nl' => 'Finland'),
			'FR' => array('code' => 'FR', 'nl' => 'Frankrijk'),
			'TF' => array('code' => 'TF', 'nl' => 'Franse Zuidelijke en Antarctische Gebieden'),
			'GF' => array('code' => 'GF', 'nl' => 'Frans-Guyana'),
			'PF' => array('code' => 'PF', 'nl' => 'Frans-PolynesiÃ«'),
			'GA' => array('code' => 'GA', 'nl' => 'Gabon'),
			'GM' => array('code' => 'GM', 'nl' => 'Gambia'),
			'GE' => array('code' => 'GE', 'nl' => 'GeorgiÃ«'),
			'GH' => array('code' => 'GH', 'nl' => 'Ghana'),
			'GI' => array('code' => 'GI', 'nl' => 'Gibraltar'),
			'GD' => array('code' => 'GD', 'nl' => 'Grenada'),
			'GR' => array('code' => 'GR', 'nl' => 'Griekenland'),
			'GL' => array('code' => 'GL', 'nl' => 'Groenland'),
			'GP' => array('code' => 'GP', 'nl' => 'Guadeloupe'),
			'GU' => array('code' => 'GU', 'nl' => 'Guam'),
			'GT' => array('code' => 'GT', 'nl' => 'Guatemala'),
			'GG' => array('code' => 'GG', 'nl' => 'Guernsey'),
			'GN' => array('code' => 'GN', 'nl' => 'Guinee'),
			'GW' => array('code' => 'GW', 'nl' => 'Guinee-Bissau'),
			'GY' => array('code' => 'GY', 'nl' => 'Guyana'),
			'HT' => array('code' => 'HT', 'nl' => 'HaÃ¯ti'),
			'HM' => array('code' => 'HM', 'nl' => 'Heard en McDonaldeilanden'),
			'HN' => array('code' => 'HN', 'nl' => 'Honduras'),
			'HU' => array('code' => 'HU', 'nl' => 'Hongarije'),
			'HK' => array('code' => 'HK', 'nl' => 'Hongkong'),
			'IE' => array('code' => 'IE', 'nl' => 'Ierland'),
			'IS' => array('code' => 'IS', 'nl' => 'IJsland'),
			'IN' => array('code' => 'IN', 'nl' => 'India'),
			'ID' => array('code' => 'ID', 'nl' => 'IndonesiÃ«'),
			'IQ' => array('code' => 'IQ', 'nl' => 'Irak'),
			'IR' => array('code' => 'IR', 'nl' => 'Iran'),
			'IL' => array('code' => 'IL', 'nl' => 'IsraÃ«l'),
			'IT' => array('code' => 'IT', 'nl' => 'ItaliÃ«'),
			'CI' => array('code' => 'CI', 'nl' => 'Ivoorkust'),
			'JM' => array('code' => 'JM', 'nl' => 'Jamaica'),
			'JP' => array('code' => 'JP', 'nl' => 'Japan'),
			'YE' => array('code' => 'YE', 'nl' => 'Jemen'),
			'JE' => array('code' => 'JE', 'nl' => 'Jersey'),
			'JO' => array('code' => 'JO', 'nl' => 'JordaniÃ«'),
			'KY' => array('code' => 'KY', 'nl' => 'Kaaimaneilanden'),
			'CV' => array('code' => 'CV', 'nl' => 'KaapverdiÃ«'),
			'CM' => array('code' => 'CM', 'nl' => 'Kameroen'),
			'KZ' => array('code' => 'KZ', 'nl' => 'Kazachstan'),
			'KE' => array('code' => 'KE', 'nl' => 'Kenia'),
			'KG' => array('code' => 'KG', 'nl' => 'KirgiziÃ«'),
			'KI' => array('code' => 'KI', 'nl' => 'Kiribati'),
			'UM' => array('code' => 'UM', 'nl' => 'Kleine Pacifische eilanden van de Verenigde Staten'),
			'KW' => array('code' => 'KW', 'nl' => 'Koeweit'),
			'HR' => array('code' => 'HR', 'nl' => 'KroatiÃ«'),
			'LA' => array('code' => 'LA', 'nl' => 'Laos'),
			'LS' => array('code' => 'LS', 'nl' => 'Lesotho'),
			'LV' => array('code' => 'LV', 'nl' => 'Letland'),
			'LB' => array('code' => 'LB', 'nl' => 'Libanon'),
			'LR' => array('code' => 'LR', 'nl' => 'Liberia'),
			'LY' => array('code' => 'LY', 'nl' => 'LibiÃ«'),
			'LI' => array('code' => 'LI', 'nl' => 'Liechtenstein'),
			'LT' => array('code' => 'LT', 'nl' => 'Litouwen'),
			'LU' => array('code' => 'LU', 'nl' => 'Luxemburg'),
			'MO' => array('code' => 'MO', 'nl' => 'Macau'),
			'MK' => array('code' => 'MK', 'nl' => 'MacedoniÃ«'),
			'MG' => array('code' => 'MG', 'nl' => 'Madagaskar'),
			'MW' => array('code' => 'MW', 'nl' => 'Malawi'),
			'MV' => array('code' => 'MV', 'nl' => 'Maldiven'),
			'MY' => array('code' => 'MY', 'nl' => 'MaleisiÃ«'),
			'ML' => array('code' => 'ML', 'nl' => 'Mali'),
			'MT' => array('code' => 'MT', 'nl' => 'Malta'),
			'IM' => array('code' => 'IM', 'nl' => 'Man'),
			'MA' => array('code' => 'MA', 'nl' => 'Marokko'),
			'MH' => array('code' => 'MH', 'nl' => 'Marshalleilanden'),
			'MQ' => array('code' => 'MQ', 'nl' => 'Martinique'),
			'MR' => array('code' => 'MR', 'nl' => 'MauritaniÃ«'),
			'MU' => array('code' => 'MU', 'nl' => 'Mauritius'),
			'YT' => array('code' => 'YT', 'nl' => 'Mayotte'),
			'MX' => array('code' => 'MX', 'nl' => 'Mexico'),
			'FM' => array('code' => 'FM', 'nl' => 'Micronesia'),
			'MD' => array('code' => 'MD', 'nl' => 'MoldaviÃ«'),
			'MC' => array('code' => 'MC', 'nl' => 'Monaco'),
			'MN' => array('code' => 'MN', 'nl' => 'MongoliÃ«'),
			'ME' => array('code' => 'ME', 'nl' => 'Montenegro'),
			'MS' => array('code' => 'MS', 'nl' => 'Montserrat'),
			'MZ' => array('code' => 'MZ', 'nl' => 'Mozambique'),
			'MM' => array('code' => 'MM', 'nl' => 'Myanmar'),
			'NA' => array('code' => 'NA', 'nl' => 'NamibiÃ«'),
			'NR' => array('code' => 'NR', 'nl' => 'Nauru'),
			'NL' => array('code' => 'NL', 'nl' => 'Nederland'),
			'NP' => array('code' => 'NP', 'nl' => 'Nepal'),
			'NI' => array('code' => 'NI', 'nl' => 'Nicaragua'),
			'NC' => array('code' => 'NC', 'nl' => 'Nieuw-CaledoniÃ«'),
			'NZ' => array('code' => 'NZ', 'nl' => 'Nieuw-Zeeland'),
			'NE' => array('code' => 'NE', 'nl' => 'Niger'),
			'NG' => array('code' => 'NG', 'nl' => 'Nigeria'),
			'NU' => array('code' => 'NU', 'nl' => 'Niue'),
			'MP' => array('code' => 'MP', 'nl' => 'Noordelijke Marianen'),
			'KP' => array('code' => 'KP', 'nl' => 'Noord-Korea'),
			'NO' => array('code' => 'NO', 'nl' => 'Noorwegen'),
			'NF' => array('code' => 'NF', 'nl' => 'Norfolk'),
			'UG' => array('code' => 'UG', 'nl' => 'Oeganda'),
			'UA' => array('code' => 'UA', 'nl' => 'OekraÃ¯ne'),
			'UZ' => array('code' => 'UZ', 'nl' => 'Oezbekistan'),
			'OM' => array('code' => 'OM', 'nl' => 'Oman'),
			'AT' => array('code' => 'AT', 'nl' => 'Oostenrijk'),
			'TL' => array('code' => 'TL', 'nl' => 'Oost-Timor'),
			'PK' => array('code' => 'PK', 'nl' => 'Pakistan'),
			'PW' => array('code' => 'PW', 'nl' => 'Palau'),
			'PS' => array('code' => 'PS', 'nl' => 'Palestijnse Autoriteit'),
			'PA' => array('code' => 'PA', 'nl' => 'Panama'),
			'PG' => array('code' => 'PG', 'nl' => 'Papoea-Nieuw-Guinea'),
			'PY' => array('code' => 'PY', 'nl' => 'Paraguay'),
			'PE' => array('code' => 'PE', 'nl' => 'Peru'),
			'PN' => array('code' => 'PN', 'nl' => 'Pitcairneilanden'),
			'PL' => array('code' => 'PL', 'nl' => 'Polen'),
			'PT' => array('code' => 'PT', 'nl' => 'Portugal'),
			'PR' => array('code' => 'PR', 'nl' => 'Puerto Rico'),
			'QA' => array('code' => 'QA', 'nl' => 'Qatar'),
			'RE' => array('code' => 'RE', 'nl' => 'RÃ©union'),
			'RO' => array('code' => 'RO', 'nl' => 'RoemeniÃ«'),
			'RU' => array('code' => 'RU', 'nl' => 'Rusland'),
			'RW' => array('code' => 'RW', 'nl' => 'Rwanda'),
			'BL' => array('code' => 'BL', 'nl' => 'Saint-BarthÃ©lemy'),
			'KN' => array('code' => 'KN', 'nl' => 'Saint Kitts en Nevis'),
			'LC' => array('code' => 'LC', 'nl' => 'Saint Lucia'),
			'PM' => array('code' => 'PM', 'nl' => 'Saint-Pierre en Miquelon'),
			'VC' => array('code' => 'VC', 'nl' => 'Saint Vincent en de Grenadines'),
			'SB' => array('code' => 'SB', 'nl' => 'Salomonseilanden'),
			'WS' => array('code' => 'WS', 'nl' => 'Samoa'),
			'SM' => array('code' => 'SM', 'nl' => 'San Marino'),
			'SA' => array('code' => 'SA', 'nl' => 'Saoedi-ArabiÃ«'),
			'ST' => array('code' => 'ST', 'nl' => 'Sao TomÃ© en Principe'),
			'SN' => array('code' => 'SN', 'nl' => 'Senegal'),
			'RS' => array('code' => 'RS', 'nl' => 'ServiÃ«'),
			'SC' => array('code' => 'SC', 'nl' => 'Seychellen'),
			'SL' => array('code' => 'SL', 'nl' => 'Sierra Leone'),
			'SG' => array('code' => 'SG', 'nl' => 'Singapore'),
			'SH' => array('code' => 'SH', 'nl' => 'Sint-Helena, Ascension en Tristan da Cunha'),
			'MF' => array('code' => 'MF', 'nl' => 'Sint-Maarten'),
			'SX' => array('code' => 'SX', 'nl' => 'Sint Maarten'),
			'SI' => array('code' => 'SI', 'nl' => 'SloveniÃ«'),
			'SK' => array('code' => 'SK', 'nl' => 'Slowakije'),
			'SD' => array('code' => 'SD', 'nl' => 'Soedan'),
			'SO' => array('code' => 'SO', 'nl' => 'SomaliÃ«'),
			'ES' => array('code' => 'ES', 'nl' => 'Spanje'),
			'SJ' => array('code' => 'SJ', 'nl' => 'Spitsbergen en Jan Mayen'),
			'LK' => array('code' => 'LK', 'nl' => 'Sri Lanka'),
			'SR' => array('code' => 'SR', 'nl' => 'Suriname'),
			'SZ' => array('code' => 'SZ', 'nl' => 'Swaziland'),
			'SY' => array('code' => 'SY', 'nl' => 'SyriÃ«'),
			'TJ' => array('code' => 'TJ', 'nl' => 'Tadzjikistan'),
			'TW' => array('code' => 'TW', 'nl' => 'Taiwan'),
			'TZ' => array('code' => 'TZ', 'nl' => 'Tanzania'),
			'TH' => array('code' => 'TH', 'nl' => 'Thailand'),
			'TG' => array('code' => 'TG', 'nl' => 'Togo'),
			'TK' => array('code' => 'TK', 'nl' => 'Tokelau-eilanden'),
			'TO' => array('code' => 'TO', 'nl' => 'Tonga'),
			'TT' => array('code' => 'TT', 'nl' => 'Trinidad en Tobago'),
			'TD' => array('code' => 'TD', 'nl' => 'Tsjaad'),
			'CZ' => array('code' => 'CZ', 'nl' => 'TsjechiÃ«'),
			'TN' => array('code' => 'TN', 'nl' => 'TunesiÃ«'),
			'TR' => array('code' => 'TR', 'nl' => 'Turkije'),
			'TM' => array('code' => 'TM', 'nl' => 'Turkmenistan'),
			'TC' => array('code' => 'TC', 'nl' => 'Turks- en Caicoseilanden'),
			'TV' => array('code' => 'TV', 'nl' => 'Tuvalu'),
			'UY' => array('code' => 'UY', 'nl' => 'Uruguay'),
			'VU' => array('code' => 'VU', 'nl' => 'Vanuatu'),
			'VA' => array('code' => 'VA', 'nl' => 'Vaticaanstad'),
			'VE' => array('code' => 'VE', 'nl' => 'Venezuela'),
			'AE' => array('code' => 'AE', 'nl' => 'Verenigde Arabische Emiraten'),
			'US' => array('code' => 'US', 'nl' => 'Verenigde Staten'),
			'GB' => array('code' => 'GB', 'nl' => 'Verenigd Koninkrijk'),
			'VN' => array('code' => 'VN', 'nl' => 'Vietnam'),
			'WF' => array('code' => 'WF', 'nl' => 'Wallis en Futuna'),
			'EH' => array('code' => 'EH', 'nl' => 'Westelijke Sahara'),
			'BY' => array('code' => 'BY', 'nl' => 'Wit-Rusland'),
			'ZM' => array('code' => 'ZM', 'nl' => 'Zambia'),
			'ZW' => array('code' => 'ZW', 'nl' => 'Zimbabwe'),
			'ZA' => array('code' => 'ZA', 'nl' => 'Zuid-Afrika'),
			'GS' => array('code' => 'GS', 'nl' => 'Zuid-Georgia en de Zuidelijke Sandwicheilanden'),
			'KR' => array('code' => 'KR', 'nl' => 'Zuid-Korea'),
			'SS' => array('code' => 'SS', 'nl' => 'Zuid-Soedan'),
			'SE' => array('code' => 'SE', 'nl' => 'Zweden'),
			'CH' => array('code' => 'CH', 'nl' => 'Zwitserland')
			);
	public static $namedentities = array ('&quot;' => '"', '&apos;' => '\'', '&amp;' => '&', '&lt;' => '<', '&gt;' => '>', '&nbsp;' => '', '&iexcl;' => 'Â¡', '&cent;' => 'Â¢',
			'&pound;' => 'Â£', '&curren;' => 'Â¤', '&yen;' => 'Â¥', '&brvbar;' => 'Â¦', '&sect;' => 'Â§', '&uml;' => 'Â¨', '&copy;' => 'Â©', '&ordf;' => 'Âª',
			'&laquo;' => 'Â«', '&not;' => 'Â¬', '&shy;' => '', '&reg;' => 'Â®', '&macr;' => 'Â¯', '&deg;' => 'Â°', '&plusmn;' => 'Â±', '&sup2;' => 'Â²',
			'&sup3;' => 'Â³', '&acute;' => 'Â´', '&micro;' => 'Âµ', '&para;' => 'Â¶', '&middot;' => 'â€¢', '&cedil;' => 'Â¸', '&sup1;' => 'Â¹', '&ordm;' => 'Âº',
			'&raquo;' => 'Â»', '&frac14;' => 'Â¼', '&frac12;' => 'Â½', '&frac34;' => 'Â¾', '&iquest;' => 'Â¿', '&times;' => 'Ã—', '&divide;' => 'Ã·',
			'&Agrave;' => 'Ã€', '&Aacute;' => 'Ã', '&Acirc;' => 'Ã‚', '&Atilde;' => 'Ãƒ', '&Auml;' => 'Ã„', '&Aring;' => 'Ã…', '&AElig;' => 'Ã†',
			'&Ccedil;' => 'Ã‡', '&Egrave;' => 'Ãˆ', '&Eacute;' => 'Ã‰', '&Ecirc;' => 'ÃŠ', '&Euml;' => 'Ã‹', '&Igrave;' => 'ÃŒ', '&Iacute;' => 'Ã',
			'&Icirc;' => 'ÃŽ', '&Iuml;' => 'Ã', '&ETH;' => 'Ã', '&Ntilde;' => 'Ã‘', '&Ograve;' => 'Ã’', '&Oacute;' => 'Ã“', '&Ocirc;' => 'Ã”', '&Otilde;' => 'Ã•',
			'&Ouml;' => 'Ã–', '&Oslash;' => 'Ã˜', '&Ugrave;' => 'Ã™', '&Uacute;' => 'Ãš', '&Ucirc;' => 'Ã›', '&Uuml;' => 'Ãœ', '&Yacute;' => 'Ã', '&THORN;' => 'Ãž',
			'&szlig;' => 'ÃŸ', '&agrave;' => 'Ã ', '&aacute;' => 'Ã¡', '&acirc;' => 'Ã¢', '&atilde;' => 'Ã£', '&auml;' => 'Ã¤', '&aring;' => 'Ã¥', '&aelig;' => 'Ã¦',
			'&ccedil;' => 'Ã§', '&egrave;' => 'Ã¨', '&eacute;' => 'Ã©', '&ecirc;' => 'Ãª', '&euml;' => 'Ã«', '&igrave;' => 'Ã¬', '&iacute;' => 'Ã­', '&icirc;' => 'Ã®',
			'&iuml;' => 'Ã¯', '&eth;' => 'Ã°', '&ntilde;' => 'Ã±', '&ograve;' => 'Ã²', '&oacute;' => 'Ã³', '&ocirc;' => 'Ã´', '&otilde;' => 'Ãµ', '&ouml;' => 'Ã¶',
			'&oslash;' => 'Ã¸', '&ugrave;' => 'Ã¹', '&uacute;' => 'Ãº', '&ucirc;' => 'Ã»', '&uuml;' => 'Ã¼', '&yacute;' => 'Ã½', '&thorn;' => 'Ã¾', '&yuml;' => 'Ã¿',
			'&forall;' => 'âˆ€', '&part;' => 'âˆ‚', '&exist;' => 'âˆƒ', '&empty;' => 'âˆ…', '&nabla;' => 'âˆ‡', '&isin;' => 'âˆˆ', '&notin;' => 'âˆ‰', '&ni;' => 'âˆ‹',
			'&prod;' => 'âˆ', '&sum;' => 'âˆ‘', '&minus;' => 'âˆ’', '&lowast;' => 'âˆ—', '&radic;' => 'âˆš', '&prop;' => 'âˆ', '&infin;' => 'âˆž', '&ang;' => 'âˆ ',
			'&and;' => 'âˆ§', '&or;' => 'âˆ¨', '&cap;' => 'âˆ©', '&cup;' => 'âˆª', '&int;' => 'âˆ«', '&there4;' => 'âˆ´', '&sim;' => 'âˆ¼', '&cong;' => 'â‰…', '&asymp;' => 'â‰ˆ',
			'&ne;' => 'â‰ ', '&equiv;' => 'â‰¡', '&le;' => 'â‰¤', '&ge;' => 'â‰¥', '&sub;' => 'âŠ‚', '&sup;' => 'âŠƒ', '&nsub;' => 'âŠ„', '&sube;' => 'âŠ†', '&supe;' => 'âŠ‡',
			'&oplus;' => 'âŠ•', '&otimes;' => 'âŠ—', '&perp;' => 'âŠ¥', '&sdot;' => 'â‹…', '&Alpha;' => 'Î‘', '&Beta;' => 'Î’', '&Gamma;' => 'Î“', '&Delta;' => 'Î”',
			'&Epsilon;' => 'Î•', '&Zeta;' => 'Î–', '&Eta;' => 'Î—', '&Theta;' => 'Î˜', '&Iota;' => 'Î™', '&Kappa;' => 'Îš', '&Lambda;' => 'Î›', '&Mu;' => 'Îœ',
			'&Nu;' => 'Î', '&Xi;' => 'Îž', '&Omicron;' => 'ÎŸ', '&Pi;' => 'Î ', '&Rho;' => 'Î¡', '&Sigma;' => 'Î£', '&Tau;' => 'Î¤', '&Upsilon;' => 'Î¥', '&Phi;' => 'Î¦',
			'&Chi;' => 'Î§', '&Psi;' => 'Î¨', '&Omega;' => 'Î©', '&alpha;' => 'Î±', '&beta;' => 'Î²', '&gamma;' => 'Î³', '&delta;' => 'Î´', '&epsilon;' => 'Îµ',
			'&zeta;' => 'Î¶', '&eta;' => 'Î·', '&theta;' => 'Î¸', '&iota;' => 'Î¹', '&kappa;' => 'Îº', '&lambda;' => 'Î»', '&mu;' => 'Î¼', '&nu;' => 'Î½', '&xi;' => 'Î¾',
			'&omicron;' => 'Î¿', '&pi;' => 'Ï€', '&rho;' => 'Ï', '&sigmaf;' => 'Ï‚', '&sigma;' => 'Ïƒ', '&tau;' => 'Ï„', '&upsilon;' => 'Ï…', '&phi;' => 'Ï†',
			'&chi;' => 'Ï‡', '&psi;' => 'Ïˆ', '&omega;' => 'Ï‰', '&thetasym;' => 'Ï‘', '&upsih;' => 'Ï’', '&piv;' => 'Ï–', '&OElig;' => 'Å’', '&oelig;' => 'Å“',
			'&Scaron;' => 'Å ', '&scaron;' => 'Å¡', '&Yuml;' => 'Å¸', '&fnof;' => 'Æ’', '&circ;' => 'Ë†', '&tilde;' => 'Ëœ', '&ensp;' => 'â€‚', '&emsp;' => 'â€ƒ',
			'&thinsp;' => 'â€‰', '&zwnj;' => '', '&zwj;' => '', '&lrm;' => 'â€Ž', '&rlm;' => 'â€', '&ndash;' => 'â€“', '&mdash;' => 'â€”', '&lsquo;' => 'â€˜', '&rsquo;' => 'â€™',
			'&sbquo;' => 'â€š', '&ldquo;' => 'â€œ', '&rdquo;' => 'â€', '&bdquo;' => 'â€ž', '&dagger;' => 'â€ ', '&Dagger;' => 'â€¡', '&bull;' => 'â€¢', '&hellip;' => 'â€¦',
			'&permil;' => 'â€°', '&prime;' => 'â€²', '&Prime;' => 'â€³', '&lsaquo;' => 'â€¹', '&rsaquo;' => 'â€º', '&oline;' => 'â€¾', '&euro;' => 'â‚¬', '&trade;' => 'â„¢',
			'&larr;' => 'â†', '&uarr;' => 'â†‘', '&rarr;' => 'â†’', '&darr;' => 'â†“', '&harr;' => 'â†”', '&crarr;' => 'â†µ', '&lceil;' => 'âŒˆ', '&rceil;' => 'âŒ‰', '&lfloor;' => 'âŒŠ',
			'&rfloor;' => 'âŒ‹', '&loz;' => 'â—Š', '&spades;' => 'â™ ', '&clubs;' => 'â™£', '&hearts;' => 'â™¥', '&diams;' => 'â™¦');
	public static $numericentities = array('&#34;' => '"', '&#39;' => '\'', '&#38;' => '&', '&#60;' => '<', '&#62;' => '>', '&#160;' => '', '&#161;' => 'Â¡', '&#162;' => 'Â¢', '&#163;' => 'Â£',
			'&#164;' => 'Â¤', '&#165;' => 'Â¥', '&#166;' => 'Â¦', '&#167;' => 'Â§', '&#168;' => 'Â¨', '&#169;' => 'Â©', '&#170;' => 'Âª', '&#171;' => 'Â«', '&#172;' => 'Â¬',
			'&#173;' => '', '&#174;' => 'Â®', '&#175;' => 'Â¯', '&#176;' => 'Â°', '&#177;' => 'Â±', '&#178;' => 'Â²', '&#179;' => 'Â³', '&#180;' => 'Â´', '&#181;' => 'Âµ',
			'&#182;' => 'Â¶', '&#183;' => 'â€¢', '&#184;' => 'Â¸', '&#185;' => 'Â¹', '&#186;' => 'Âº', '&#187;' => 'Â»', '&#188;' => 'Â¼', '&#189;' => 'Â½', '&#190;' => 'Â¾',
			'&#191;' => 'Â¿', '&#215;' => 'Ã—', '&#247;' => 'Ã·', '&#192;' => 'Ã€', '&#193;' => 'Ã', '&#194;' => 'Ã‚', '&#195;' => 'Ãƒ', '&#196;' => 'Ã„', '&#197;' => 'Ã…',
			'&#198;' => 'Ã†', '&#199;' => 'Ã‡', '&#200;' => 'Ãˆ', '&#201;' => 'Ã‰', '&#202;' => 'ÃŠ', '&#203;' => 'Ã‹', '&#204;' => 'ÃŒ', '&#205;' => 'Ã', '&#206;' => 'ÃŽ',
			'&#207;' => 'Ã', '&#208;' => 'Ã', '&#209;' => 'Ã‘', '&#210;' => 'Ã’', '&#211;' => 'Ã“', '&#212;' => 'Ã”', '&#213;' => 'Ã•', '&#214;' => 'Ã–', '&#216;' => 'Ã˜',
			'&#217;' => 'Ã™', '&#218;' => 'Ãš', '&#219;' => 'Ã›', '&#220;' => 'Ãœ', '&#221;' => 'Ã', '&#222;' => 'Ãž', '&#223;' => 'ÃŸ', '&#224;' => 'Ã ', '&#225;' => 'Ã¡',
			'&#226;' => 'Ã¢', '&#227;' => 'Ã£', '&#228;' => 'Ã¤', '&#229;' => 'Ã¥', '&#230;' => 'Ã¦', '&#231;' => 'Ã§', '&#232;' => 'Ã¨', '&#233;' => 'Ã©', '&#234;' => 'Ãª',
			'&#235;' => 'Ã«', '&#236;' => 'Ã¬', '&#237;' => 'Ã­', '&#238;' => 'Ã®', '&#239;' => 'Ã¯', '&#240;' => 'Ã°', '&#241;' => 'Ã±', '&#242;' => 'Ã²', '&#243;' => 'Ã³',
			'&#244;' => 'Ã´', '&#245;' => 'Ãµ', '&#246;' => 'Ã¶', '&#248;' => 'Ã¸', '&#249;' => 'Ã¹', '&#250;' => 'Ãº', '&#251;' => 'Ã»', '&#252;' => 'Ã¼', '&#253;' => 'Ã½',
			'&#254;' => 'Ã¾', '&#255;' => 'Ã¿', '&#8704;' => 'âˆ€', '&#8706;' => 'âˆ‚', '&#8707;' => 'âˆƒ', '&#8709;' => 'âˆ…', '&#8711;' => 'âˆ‡', '&#8712;' => 'âˆˆ', '&#8713;' => 'âˆ‰',
			'&#8715;' => 'âˆ‹', '&#8719;' => 'âˆ', '&#8721;' => 'âˆ‘', '&#8722;' => 'âˆ’', '&#8727;' => 'âˆ—', '&#8730;' => 'âˆš', '&#8733;' => 'âˆ', '&#8734;' => 'âˆž', '&#8736;' => 'âˆ ',
			'&#8743;' => 'âˆ§', '&#8744;' => 'âˆ¨', '&#8745;' => 'âˆ©', '&#8746;' => 'âˆª', '&#8747;' => 'âˆ«', '&#8756;' => 'âˆ´', '&#8764;' => 'âˆ¼', '&#8773;' => 'â‰…', '&#8776;' => 'â‰ˆ',
			'&#8800;' => 'â‰ ', '&#8801;' => 'â‰¡', '&#8804;' => 'â‰¤', '&#8805;' => 'â‰¥', '&#8834;' => 'âŠ‚', '&#8835;' => 'âŠƒ', '&#8836;' => 'âŠ„', '&#8838;' => 'âŠ†', '&#8839;' => 'âŠ‡',
			'&#8853;' => 'âŠ•', '&#8855;' => 'âŠ—', '&#8869;' => 'âŠ¥', '&#8901;' => 'â‹…', '&#913;' => 'Î‘', '&#914;' => 'Î’', '&#915;' => 'Î“', '&#916;' => 'Î”', '&#917;' => 'Î•',
			'&#918;' => 'Î–', '&#919;' => 'Î—', '&#920;' => 'Î˜', '&#921;' => 'Î™', '&#922;' => 'Îš', '&#923;' => 'Î›', '&#924;' => 'Îœ', '&#925;' => 'Î', '&#926;' => 'Îž',
			'&#927;' => 'ÎŸ', '&#928;' => 'Î ', '&#929;' => 'Î¡', '&#931;' => 'Î£', '&#932;' => 'Î¤', '&#933;' => 'Î¥', '&#934;' => 'Î¦', '&#935;' => 'Î§', '&#936;' => 'Î¨',
			'&#937;' => 'Î©', '&#945;' => 'Î±', '&#946;' => 'Î²', '&#947;' => 'Î³', '&#948;' => 'Î´', '&#949;' => 'Îµ', '&#950;' => 'Î¶', '&#951;' => 'Î·', '&#952;' => 'Î¸',
			'&#953;' => 'Î¹', '&#954;' => 'Îº', '&#955;' => 'Î»', '&#956;' => 'Î¼', '&#957;' => 'Î½', '&#958;' => 'Î¾', '&#959;' => 'Î¿', '&#960;' => 'Ï€', '&#961;' => 'Ï',
			'&#962;' => 'Ï‚', '&#963;' => 'Ïƒ', '&#964;' => 'Ï„', '&#965;' => 'Ï…', '&#966;' => 'Ï†', '&#967;' => 'Ï‡', '&#968;' => 'Ïˆ', '&#969;' => 'Ï‰', '&#977;' => 'Ï‘',
			'&#978;' => 'Ï’', '&#982;' => 'Ï–', '&#338;' => 'Å’', '&#339;' => 'Å“', '&#352;' => 'Å ', '&#353;' => 'Å¡', '&#376;' => 'Å¸', '&#402;' => 'Æ’', '&#710;' => 'Ë†',
			'&#732;' => 'Ëœ', '&#8211;' => 'â€“','&#8212;' => 'â€”','&#8216;' => 'â€˜','&#8217;' => 'â€™','&#8218;' => 'â€š','&#8220;' => 'â€œ','&#8221;' => 'â€','&#8222;' => 'â€ž',
			'&#8224;' => 'â€ ','&#8225;' => 'â€¡','&#8226;' => 'â€¢','&#8230;' => 'â€¦','&#8240;' => 'â€°','&#8242;' => 'â€²','&#8243;' => 'â€³','&#8249;' => 'â€¹','&#8250;' => 'â€º',
			'&#8254;' => 'â€¾','&#8364;' => 'â‚¬','&#8482;' => 'â„¢','&#8592;' => 'â†','&#8593;' => 'â†‘','&#8594;' => 'â†’','&#8595;' => 'â†“','&#8596;' => 'â†”','&#8629;' => 'â†µ',
			'&#8968;' => 'âŒˆ','&#8969;' => 'âŒ‰','&#8970;' => 'âŒŠ','&#8971;' => 'âŒ‹','&#9674;' => 'â—Š','&#9824;' => 'â™ ','&#9827;' => 'â™£','&#9829;' => 'â™¥','&#9830;' => 'â™¦');
	
	public static $uppertolowerent =  array("ÄŒ" => "Ä", "ÄŽ" => "Ä", "Äš" => "Ä›", "Ä½" => "Ä¾", "Å‡" => "Åˆ", "Å˜" => "Å™", "Å " => "Å¡", "Å¤" => "Å¥", "Å½" => "Å¾","Ã„" => "Ã¤", "Ã–" => "Ã¶", "Ãœ" => "Ã¼",
			"&Auml;" => "Ã¤", "&#196;" => "Ã¤", "&Ouml;" => "Ã¶", "&#214;" => "Ã¶", "&Uuml;" => "Ã¼", "&#220;" => "Ã¼","Ã€" => "Ã ", "Ãˆ" => "Ã¨", "ÃŒ" => "Ã¬", "Ã’" => "Ã²", "Ã™" => "Ã¹",
			"Ã‰" => "Ã©", "Ã" => "Ã­", "Ã“" => "Ã³", "Ãš" => "Ãº", "Ãƒ" => "Ã£", "Ã‘" => "Ã±", "Ã•" => "Ãµ", "Å¨" => "Å©", "Ã‚" => "Ã¢", "ÃŠ" => "Ãª", "ÃŽ" => "Ã®", "Ã”" => "Ã´", "Ã›" => "Ã»",
			"Ã…" => "Ã¥", "Å®" => "Å¯", "Ã†" => "Ã¦", "Ã‡" => "Ã§", "Ã˜" => "Ã¸", "Ã‹" => "Ã«", "Ã" => "Ã¯", "Äž" => "ÄŸ", "Ä°" => "i", "Åž" => "ÅŸ", "Ä¦" => "Ä§", "Ä¤" => "Ä¥", "Ä´" => "Äµ",
			"Å»" => "Å¼", "ÄŠ" => "Ä‹", "Äˆ" => "Ä‰", "Å¬" => "Å­", "Åœ" => "Å", "Ä‚" => "Äƒ", "Å" => "Å‘", "Ä¹" => "Äº", "Ä†" => "Ä‡", "Å°" => "Å±", "Å¢" => "Å£", "Åƒ" => "Å„", "Ä" => "Ä‘",
			"Å”" => "Å•", "Ã" => "Ã¡", "Åš" => "Å›", "Å¹" => "Åº", "Å" => "Å‚", "Ë˜" => "Ë›", "Ä¸" => "Ë›", "Å–" => "Å—", "Ä®" => "Ä¯", "Ä˜" => "Ä™", "Ä–" => "Ä—", "Ã" => "Ã°","Å…" => "Å†",
			"ÅŒ" => "Å", "Å²" => "Å³", "Ã" => "Ã½", "Ãž" => "Ã¾", "Ä„" => "Ä…", "Ä’" => "Ä“", "Ä¢" => "Ä£", "Äª" => "Ä«", "Ä¨" => "Ä©", "Ä¶" => "Ä·", "Ä»" => "Ä¼", "Å¦" => "Å§", "Åª" => "Å«",
			"ÅŠ" => "Å‹", "Ä€" => "Ä", "á¸‚" => "á¸ƒ", "á¸Š" => "á¸‹", "áº€" => "áº", "áº‚" => "áºƒ", "á¹ " => "á¹¡", "á¸ž" => "á¸Ÿ", "á¹€" => "á¹", "á¹–" => "á¹—", "áº„" => "áº…", "Å´" => "Åµ", "á¹ª" => "á¹«", "Å¶" => "Å·");
	
	public static $uppertolowergreek = array("Î‘" => "Î±", "Î’" => "Î²", "Î“" => "Î³", "Î”" => "Î´", "Î•" => "Îµ", "Î–" => "Î¶", "Î—" => "Î·", "Î˜" => "Î¸", "Î™" => "Î¹", "Îš" => "Îº", "Î›" => "Î»", "Îœ" => "Î¼",
			"Î" => "Î½", "Îž" => "Î¾", "ÎŸ" => "Î¿", "Î " => "Ï€", "Î¡" => "Ï", "Î£" => "Ïƒ", "Î¤" => "Ï„", "Î¥" => "Ï…", "Î¦" => "Ï†", "Î§" => "Ï‡", "Î¨Ïˆ" => "","Î©" => "Ï‰");
	
	public static $upptertolowercyrillic = array(
			//      basic Cyrillian alphabet
			"Ð" => "Ð°", "Ð‘" => "Ð±", "Ð’" => "Ð²", "Ð“" => "Ð³", "Ò" => "Ò‘", "Ðƒ" => "Ñ“", "Ð”" => "Ð´", "Ð‚" => "Ñ’", "Ð•" => "Ðµ", "Ð" => "Ñ‘", "Ð„" => "Ñ”", "Ð–" => "Ð¶",
			"Ð—" => "Ð·", "Ð…" => "Ñ•", "Ð˜" => "Ð¸", "Ð†" => "Ñ–", "Ð‡" => "Ñ—", "Ð™" => "Ð¹", "Ðˆ" => "Ñ˜", "Ðš" => "Ðº", "ÐŒ" => "Ñœ", "Ð›" => "Ð»", "Ð‰" => "Ñ™", "Ðœ" => "Ð¼","Ð" => "Ð½",
			"ÐŠ" => "Ñš", "Ðž" => "Ð¾", "ÐŸ" => "Ð¿", "Ð " => "Ñ€", "Ð¡" => "Ñ", "Ð¢" => "Ñ‚", "Ð‹" => "Ñ›", "Ð£" => "Ñƒ", "ÐŽ" => "Ñž", "Ð¤" => "Ñ„", "Ð¥" => "Ñ…", "Ñ " => "Ñ¡",          //     ex Greek 'OMEGA'
			"Ð¦" => "Ñ†", "Ð§" => "Ñ‡", "Ð" => "ÑŸ", "Ð¨" => "Ñˆ", "Ð©" => "Ñ‰", "Ðª" => "ÑŠ", "Ð«" => "Ñ‹", "Ð¬" => "ÑŒ", "Ð«" => "Ñ‹", "Ð­" => "Ñ", "Ð®" => "ÑŽ", "Ð¯" => "Ñ",
			"Ð€" => "Ñ", "Ð‚" => "Ñ’", "Ð‡" => "Ñ—", "Ð" => "Ñ",
			"Ñ¤" => "Ñ¥",         //      extended Cyrillic
			"Ñ¦" => "Ñ§", "Ñª" => "Ñ«", "Ñ¨" => "Ñ©", "Ñ¬" => "Ñ­", "Ñ®" => "Ñ¯", "Ñ°" => "Ñ±", "Ñ²" => "Ñ³", "Ñ´" => "Ñµ",
			"Ä" => "Ä‘", "Ç´" => "Çµ", "ÃŠ" => "Ãª", "áº" => "áº‘", "ÃŒ" => "Ã¬", "Ã" => "Ã¯", "JË‡" => "Ç°", "LÌ‚" => "lÌ‚", "NÌ‚" => "nÌ‚", "Ä†" => "Ä‡", "á¸°" => "á¸±", "Å¬" => "Å­",
			"DÌ‚" => "dÌ‚", "Åœ" => "Å", "Ã›" => "Ã»", "Ã‚" => "Ã¢", "GÌ€" => "g", "Äš" => "Ä›", "GÌ€" => "g", "Ä " => "Ä¡", "Äž" => "ÄŸ", "Å½Ì¦" => "Å¾", "Ä¶" => "Ä·", "KÌ„" => "kÌ„",
			"á¹†" => "á¹‡", "á¹„" => "á¹…", "á¹”" => "á¹•", "Ã’" => "Ã²", "Ã‡" => "Ã§", "Å¢" => "Å£", "Ã™" => "Ã¹", "U" => "u", "á¸¨" => "á¸©", "CÌ„" => "cÌ„", "á¸¤" => "á¸¥", "CÌ†" => "cÌ†",
			"Ã‡Ì†" => "Ã§Ì†", "ZÌ†" => "zÌ†", "Ä‚" => "Äƒ", "Ã„" => "Ã¤", "Ä”" => "Ä•", "ZÌ„" => "zÌ„", "ZÌˆ" => "zÌˆ", "Å¹" => "Åº", "ÃŽ" => "Ã®", "Ã–" => "Ã¶", "Ã”" => "Ã´", "Ãœ" => "Ã¼",
			"Å°" => "Å±", "CÌˆ" => "cÌˆ", "Å¸" => "Ã¿", "ÒŠ" => "Ò‹", "ÒŒ" => "Ò", "ÒŽ" => "Ò", "Ò" => "Ò‘", "Ò’" => "Ò“", "Ò”" => "Ò•", "Ò–" => "Ò—", "Ò˜" => "Ò™", "Òš" => "Ò›",
			"Òœ" => "Ò", "Òž" => "ÒŸ", "Ò " => "Ò¡", "Ò¢" => "Ò£", "Ò¤" => "Ò¥", "Ò¦" => "Ò§", "Ò¨" => "Ò©", "Òª" => "Ò«", "Ò¬" => "Ò­", "Ò®" => "Ò¯", "Ò°" => "Ò±", "Ò²" => "Ò³",
			"Ò´" => "Òµ", "Ò¶" => "Ò·", "Ò¸" => "Ò¹", "Òº" => "Ò»", "Ò¼" => "Ò½", "Ò¾" => "Ò¿", "Ó" => "Ó‚", "Óƒ" => "Ó„", "Ó…" => "Ó†", "Ó‡" => "Óˆ", "Ó‰" => "ÓŠ", "Ó‹" => "ÓŒ",
			"Ó" => "ÓŽ", "Ó" => "Ó‘", "Ó’" => "Ó“", "Ó”" => "Ó•", "Ó–" => "Ó—", "Ó˜" => "Ó™", "Óš" => "Ó›", "Óœ" => "Ó", "Óž" => "ÓŸ", "Ó " => "Ó¡", "Ó¢" => "Ó£", "Ó¤" => "Ó¥",
			"Ó¦" => "Ó§", "Ó¨" => "Ó©", "Óª" => "Ó«", "Ó¬" => "Ó­", "Ó®" => "Ó¯", "Ó°" => "Ó±", "Ó²" => "Ó³", "Ó´" => "Óµ", "Ó¶" => "Ó·", "Ó¸" => "Ó¹", "Ó¼" => "Ó½", "Ó¾" => "Ó¿",
			"Ñ " => "Ñ¡",         //      historical Cyrillic
			"Ñ¢" => "Ñ£", "Ñ¤" => "Ñ¥", "Ñ¦" => "Ñ§", "Ñ¨" => "Ñ©", "Ñª" => "Ñ«", "Ñ¬" => "Ñ­", "Ñ®" => "Ñ¯", "Ñ°" => "Ñ±", "Ñ²" => "Ñ³", "Ñ´" => "Ñµ", "Ñ¶" => "Ñ·", "Ñ¸" => "Ñ¹",
			"Ñº" => "Ñ»", "Ñ¼" => "Ñ½", "Ñ¾" => "Ñ¿", "Ò€" => "Ò", "Ç" => "ÇŽ", "FÌ€" => "fÌ€", "á»²" => "á»³",  "Ã?" => "ÃÂ°", "Ãâ€˜" => "ÃÂ±", "Ãâ€™" => "ÃÂ²", "Ãâ€œ" => "ÃÂ³",
			"Ãâ€" => "ÃÂ´", "Ãâ€¢" => "ÃÂµ", "Ãâ€“" => "ÃÂ¶", "Ãâ€”" => "ÃÂ·", "ÃËœ" => "ÃÂ¸", "Ãâ„¢" => "ÃÂ¹", "ÃÅ¡" => "ÃÂº", "Ãâ€º" => "ÃÂ»", "ÃÅ“" => "ÃÂ½", "ÃÅ¾" => "ÃÂ¾",
			"ÃÅ¸" => "ÃÂ¿", "ÃÂ " => "Ã‘â‚¬", "ÃÂ¡" => "Ã‘?", "ÃÂ¢" => "Ã‘â€š", "ÃÂ£" => "Ã‘Æ’", "ÃÂ¤" => "Ã‘â€ž", "ÃÂ¥" => "Ã‘â€¦", "ÃÂ¦" => "Ã‘â€ ", "ÃÂ§" => "Ã‘â€¡", "ÃÂ¨" => "Ã‘Ë†",
			"ÃÂ©" => "Ã‘â€°", "ÃÂª" => "Ã‘Å ", "ÃÂ«" => "Ã‘â€¹", "ÃÂ¬" => "Ã‘Å’", "ÃÂ­" => "Ã‘?", "ÃÂ®" => "Ã‘Å½", "ÃÂ¯" => "Ã‘?",  "Ã?" => "Ã‘â€˜", "Ãâ€š" => "Ã‘â€™", "ÃÆ’" => "Ã‘â€œ",
			"Ãâ€ž" => "Ã‘â€", "Ãâ€¦" => "Ã‘â€¢", "Ãâ€ " => "Ã‘â€“", "Ãâ€¡" => "Ã‘â€”", "ÃË†" => "Ã‘Ëœ", "Ãâ€°" => "Ã‘â„¢", "ÃÅ " => "Ã‘Å¡", "Ãâ€¹" => "Ã‘â€º", "ÃÅ’" => "Ã‘Å“", "ÃÅ½" => "Ã‘Å¾", "Ã?" => "Ã‘Å¸");
}